# Generated by Django 3.2.8 on 2021-10-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Resultado',
            field=models.BooleanField(),
        ),
    ]
