# Generated by Django 3.2.8 on 2021-10-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0003_alter_equipo_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Resultado',
            field=models.BooleanField(),
        ),
    ]
